# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab3App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('filmCreations_id', models.IntegerField(db_column='FilmCreations_Id')),
                ('filmHistory', models.CharField(blank=True, db_column='FilmHistory', max_length=80, null=True)),
                ('directorHistory', models.CharField(blank=True, db_column='DirectorHistory', max_length=80, null=True)),
                ('studioHistory', models.CharField(blank=True, db_column='StudioHistory', max_length=80, null=True)),
                ('date', models.DateTimeField(db_column='Date')),
            ],
            options={
                'db_table': 'History',
                'managed': False,
            },
        ),
    ]
